describe('angularjs homepage todo list', function() {
    it('Auth', function() {
      browser.waitForAngularEnabled(false);
      browser.get('http://localhost/litecart/admin/');
      element(by.css('input[name="username"]')).sendKeys('admin');
      element(by.css('input[name="password"]')).sendKeys('admin');
      element(by.css('button[name="login"]')).click();
    });

    it('Menu', function() {
      var h1 = $('td#content > h1');
      $('#box-apps-menu > li:first-child').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-logotype').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(2)').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-product_groups').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-option_groups').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-manufacturers').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-suppliers').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-delivery_statuses').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-sold_out_statuses').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-quantity_units').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-csv').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(3)').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(4)').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(5)').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-csv').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-newsletter').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(6)').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(7)').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-storage_encoding').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(8)').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-customer').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-shipping').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-payment').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-order_total').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-order_success').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-order_action').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(9)').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-order_statuses').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(10)').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(11)').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-most_sold_products').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-most_shopping_customers').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(12)').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-defaults').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-general').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-listings').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-images').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-checkout').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-advanced').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-security').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(13)').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(14)').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-tax_rates').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(15)').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-scan').click();
      expect(h1.isPresent()).toBe(true);
      $('#doc-csv').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(16)').click();
      expect(h1.isPresent()).toBe(true);
      $('#box-apps-menu > li:nth-child(17)').click();
      expect(h1.isPresent()).toBe(true);
    });
});